# Generated by Django 6.0.7 on 2026-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_featurehighlight_herosection_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurehighlight',
            name='image',
            field=models.ImageField(blank=True, help_text="Illustration icon (preferred — matches the live site's design)", null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='featurehighlight',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or emoji, used only if no image is set', max_length=50),
        ),
    ]
