# Generated by Django 6.0.7 on 2026-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('water_slides', 'Water Slides'), ('lazy_river', 'Lazy River'), ('kiddie_zone', 'Kiddie Splash Zone'), ('dining', 'Dining & Delights'), ('events', 'Events'), ('general', 'General')], default='general', max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False, help_text='Show in homepage gallery preview')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
