# Generated by Django 6.0.7 on 2026-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessibility & SEO description of the image', max_length=150),
        ),
    ]
