# Generated by Django 6.0.7 on 2026-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='link_url',
            field=models.CharField(blank=True, help_text="Optional: where this card links to when used as a homepage preview card, e.g. '/attractions'", max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show in homepage gallery/attractions preview'),
        ),
    ]
