# Generated by Django 6.0.7 on 2026-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='age_group',
            field=models.CharField(blank=True, help_text="e.g. '13+', '3-12', 'Under 3'", max_length=50),
        ),
    ]
